app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /

goods:
   type: rest
   resource: AppBundle\Controller\GoodsController
   host: localhost
fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
gesdinet_jwt_refresh_token:
    path:     /token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }